version: '3.7'

services:
  db:
    image: postgres:12.1
    hostname: db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: project_with_ts

networks:
  default:
    driver: bridge